name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build (Node ${{ matrix.node-version }} - Nest ${{ matrix.nest-version }} - Mongo ${{ matrix.mongo-version }})"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        nest-version: [^8.0.0, ^9.0.0, ^10.0.0]
        mongo-version: [^4.0.0, ^5.0.0, ^6.0.0]

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Setup: pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: "Setup: Node ${{ matrix.node-version }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Dependencies
        run: pnpm install --frozen-lockfile

      - name: "Dependencies: peer"
        run: |
          pnpm install \
            @nestjs/common@${{ matrix.nest-version }} \
            @nestjs/core@${{ matrix.nest-version }} \
            @nestjs/testing@${{ matrix.nest-version }} \
            @golee/mongo-nest mongodb@${{matrix.mongo-version}}

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: write

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip-publish]')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Setup: pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: "Setup: Node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: "Release: Prepare"
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github'
          pnpm version patch

      - name: Dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish
        run: |
          npm install -g npm@latest
          pnpm publish --no-git-checks

      - name: "Release: Perform"
        run: git push --follow-tags --no-verify
